# Generated by Django 4.2.2 on 2023-10-07 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='name',
        ),
    ]
